### ISSUE TITLE
crash on `foo???`

### ISSUE THREAD

**Issue by anntzer** [Calysto/metakernel#104]
Minimal example:

```
$ jupyter console --kernel=metakernel_python
Jupyter console 5.0.0

MetaKernel Python - evaluates Python statements and expressions


In [1]: sum???
      : 
[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/lib/python3.5/site-packages/metakernel/_metakernel.py", line 322, in do_execute
    text = self.get_help_on(code, level)
  File "/usr/lib/python3.5/site-packages/metakernel/_metakernel.py", line 678, in get_help_on
    return help_magic.get_help_on(expr, level, none_on_fail, cursor_pos)
  File "/usr/lib/python3.5/site-packages/metakernel/magics/help_magic.py", line 105, in get_help_on
    return magic.get_help_on(info)
TypeError: get_help_on() missing 1 required positional argument: 'level'
```

IPython would just report a SyntaxError and go on.

**Comment by dsblank** [comment]
This is great to have bug reports like this... thank you! This will really help add the polish we want to have on any metakernel-based language.

This is also one that should be fairly easy to fix. I guess we should create some tags, such as "sprint friendly"...

**Comment by anntzer** [comment]
FWIW I'd either rename the `level` (int) argument used throught the helpmagic to a boolean, `detailed`, or I guess you could actually allow arbitrary levels of help (not sure it would really be useful in practice).
