### ISSUE TITLE
Use the mongo cli inside the linux shell

### ISSUE THREAD

**Issue by ElouanL** [Calysto/metakernel#112]
I would like to use the mongodb CLI in jupyter. I can do it with the metakernel but the kernel crash after the frist command.

![image](https://cloud.githubusercontent.com/assets/5980071/18961686/238d282c-866e-11e6-9aa0-5b67eec98646.png)

Is this normal?

**Comment by dsblank** [comment]
You are using the bash_kernel?

**Comment by ElouanL** [comment]
I use MetaKernel Bash. I tried with the bash_kernel but I have the same issue.

This is my logs :

> [IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/metakernel/pexpect.py", line 225, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.4/dist-packages/metakernel/pexpect.py", line 1122, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
metakernel.pexpect.TIMEOUT: Timeout exceeded.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelbase.py", line 212, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelbase.py", line 370, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.4/dist-packages/metakernel/_metakernel.py", line 362, in do_execute
    retval = self.do_execute_direct(code)
  File "/usr/local/lib/python3.4/dist-packages/metakernel_bash.py", line 34, in do_execute_direct
    resp = shell_magic.eval(code.strip())
  File "/usr/local/lib/python3.4/dist-packages/metakernel/magics/shell_magic.py", line 54, in eval
    return self.repl.run_command(cmd, stream_handler=self.kernel.Print)
  File "/usr/local/lib/python3.4/dist-packages/metakernel/replwrap.py", line 126, in run_command
    return self._run_split_command(command, timeout, stream_handler)
  File "/usr/local/lib/python3.4/dist-packages/metakernel/replwrap.py", line 183, in _run_split_command
    expect_line=expect_line)
  File "/usr/local/lib/python3.4/dist-packages/metakernel/replwrap.py", line 102, in _expect_prompt
    return self.child.expect(expects, timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/metakernel/pexpect.py", line 1655, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python3.4/dist-packages/metakernel/pexpect.py", line 1676, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.4/dist-packages/metakernel/pexpect.py", line 232, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.4/dist-packages/metakernel/pexpect.py", line 197, in timeout
    raise TIMEOUT(msg)
metakernel.pexpect.TIMEOUT: Timeout exceeded.
<metakernel.pexpect.spawnu object at 0x7eff265274a8>
version: 3.3
command: /bin/bash
args: ['/bin/bash']
searcher: None
buffer (last 100 chars): '> '
before (last 100 chars): '> '
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 80
child_fd: 33
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1


Thanks

**Comment by dsblank** [comment]
The bash metakernel shell isn't designed to work this way. I think you might want to make a special mongo kernel.
