### ISSUE TITLE
Python autocompletion requires jedi >= 0.10.0

### ISSUE THREAD

**Issue by QuLogic** [Calysto/metakernel#136]
I can't figure out what's wrong here, but I can consistently reproduce this problem on both Python 2 and Python 3:
```pytb
======================================================================
FAIL: metakernel.magics.tests.test_python_magic.test_python_magic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/metakernel-0.19.1/metakernel/magics/tests/test_python_magic.py", line 12, in test_python_magic
    assert 'import' in comp['matches']
AssertionError
```
`comp['matches']` is an empty list.

**Comment by QuLogic** [comment]
OK, after a bit of digging, I think I've figured out the problem. The dependencies only list `jedi` with no specific version, and Fedora has `jedi` 0.9.0. I did find that the history shows "support for" 0.10.0, but not that it's a hard requirement, so this may not have been intentional.

The Python completion code uses `from jedi.api.helpers import get_on_completion_name`, but this function was only added in `jedi` 0.10.0. Consequently, it does not import and the completions return an empty list.

I guess to support `jedi` 0.9.0, some kind of reversal and hybrid combination of #129 needs to be made.
