### ISSUE TITLE
MetaKernel Python input and raw_input doesn't work

### ISSUE THREAD

**Issue by dsblank** [Calysto/metakernel#64]
The error:
```
%%python
input("Ok:")
```
gives:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/metakernel-0.6.1-py2.7.egg/metakernel/magics/python_magic.py", line 50, in eval
    exec(code.strip(), self.env)
  File "<string>", line 1, in <module>
EOFError: EOF when reading a line
```
I think we need to monkey patch (replace) them to work with our input methods.

**Comment by dsblank** [comment]
Fixed in 43cb9b2211eaa3902b1f92658ac20c0ed0d49f28
