### ISSUE TITLE
kernel crashes with latest notebook version

### ISSUE THREAD

**Issue by KimStebel** [Calysto/metakernel#74]
I'm trying to run this kernel using the latest `jupyter/notebook` docker image (built from current master) as a base. I've added `RUN pip2 install metakernel_bash` to my Dockerfile to install the kernel. When I run the notebook, the kernel is installed. When I create a new notebook with the kernel, it crashes and gives me this log message:

```
/usr/local/lib/python3.4/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/usr/local/lib/python3.4/dist-packages/metakernel/_metakernel.py:23: UserWarning: Cannot load module widgets so metakernel will not be available to IPython/jupyter.
  warnings.warn("Cannot load module {name} so metakernel will not be available to IPython/jupyter.".format(name=getattr(e, 'name', '')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/application.py", line 185, in __init__
    super(BaseIPythonApplication, self).__init__(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 242, in __init__
    SingletonConfigurable.__init__(self, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 74, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 588, in __init__
    setattr(self, key, value)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 961, in validate
    self.error(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'kernel_class' trait of an IPKernelApp instance must be a subclass of 'ipykernel.kernelbase.Kernel', but a value of class 'type' (i.e. <class '__main__.MetaKernelBash'>) was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/metakernel_bash.py", line 60, in <module>
    IPKernelApp.launch_instance(kernel_class=MetaKernelBash)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 590, in launch_instance
    app = cls.instance(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 380, in instance
    inst = cls(*args, **kwargs)
  File "<decorator-gen-6>", line 2, in __init__
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 77, in catch_config_error
    app.print_help()
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 349, in print_help
    self.print_options()
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 320, in print_options
    self.print_alias_help()
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 284, in print_alias_help
    cls = classdict[classname]
KeyError: 'IPKernelApp'
[W 12:30:08.255 NotebookApp] Timeout waiting for kernel_info reply from b7ba744a-eec1-4c0e-8493-c4bc5b8ca945
[I 12:30:10.179 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel b7ba744a-eec1-4c0e-8493-c4bc5b8ca945 restarted
/usr/local/lib/python3.4/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/usr/local/lib/python3.4/dist-packages/metakernel/_metakernel.py:23: UserWarning: Cannot load module widgets so metakernel will not be available to IPython/jupyter.
  warnings.warn("Cannot load module {name} so metakernel will not be available to IPython/jupyter.".format(name=getattr(e, 'name', '')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/application.py", line 185, in __init__
    super(BaseIPythonApplication, self).__init__(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 242, in __init__
    SingletonConfigurable.__init__(self, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 74, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 588, in __init__
    setattr(self, key, value)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 961, in validate
    self.error(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'kernel_class' trait of an IPKernelApp instance must be a subclass of 'ipykernel.kernelbase.Kernel', but a value of class 'type' (i.e. <class '__main__.MetaKernelBash'>) was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/metakernel_bash.py", line 60, in <module>
    IPKernelApp.launch_instance(kernel_class=MetaKernelBash)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 590, in launch_instance
    app = cls.instance(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 380, in instance
    inst = cls(*args, **kwargs)
  File "<decorator-gen-6>", line 2, in __init__
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 77, in catch_config_error
    app.print_help()
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 349, in print_help
    self.print_options()
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 320, in print_options
    self.print_alias_help()
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 284, in print_alias_help
    cls = classdict[classname]
KeyError: 'BaseIPythonApplication'
IPython: an enhanced interactive Python shell.

Subcommands
-----------

Subcommands are launched as `ipython-kernel cmd [args]`. For information on
using subcommand 'cmd', do: `ipython-kernel cmd -h`.

install
    Install the IPython kernel

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--matplotlib
    Configure matplotlib for interactive use with
    the default matplotlib backend.
--no-stderr
    redirect stderr to the null device
--autoindent
    Turn on autoindenting.
--automagic
    Turn on the auto calling of magic commands. Type %%magic at the
    IPython  prompt  for  more information.
--color-info
    IPython can display information about objects via a set of functions,
    and optionally can use colors for this, syntax highlighting
    source code and various other elements. This is on by default, but can cause
    problems with some pagers. If you see such problems, you can disable the
    colours.
--no-secure
    Don't authenticate messages.
--pylab
    Pre-load matplotlib and numpy for interactive use with
    the default matplotlib backend.
--no-color-info
    Disable using colors for info related things.
--deep-reload
    **Deprecated** Enable deep (recursive) reloading by default. IPython can use the
    deep_reload module which reloads changes in modules recursively (it
    replaces the reload() function, so you don't need to change anything to
    use it). deep_reload() forces a full reload of modules whose code may
    have changed, which the default reload() function does not.  When
    deep_reload is off, IPython will use the normal reload(), but
    deep_reload will still be available as dreload(). This feature is off
    by default [which means that you have both normal reload() and
    dreload()].
--pydb
    Use the third party 'pydb' package as debugger, instead of pdb.
    Requires that pydb is installed.
--init
    Initialize profile with default config files.  This is equivalent
    to running `ipython profile create <profile>` prior to startup.
--no-autoindent
    Turn off autoindenting.
--no-deep-reload
    Disable deep (recursive) reloading by default.
--no-stdout
    redirect stdout to the null device
--no-automagic
    Turn off the auto calling of magic commands.
--no-pdb
    Disable auto calling the pdb debugger after every exception.
--nosep
    Eliminate all spacing between prompts.
--no-pprint
    Disable auto pretty printing of results.
--debug
    set log level to logging.DEBUG (maximize logging output)
--secure
    Use HMAC digests for authentication of messages.
    Setting this flag will generate a new UUID to use as the HMAC key.
--pdb
    Enable auto calling the pdb debugger after every exception.
--quiet
    set log level to logging.CRITICAL (minimize logging output)
--pprint
    Enable auto pretty printing of results.
[W 12:30:13.188 NotebookApp] KernelRestarter: restart failed
[W 12:30:13.189 NotebookApp] Kernel b7ba744a-eec1-4c0e-8493-c4bc5b8ca945 died, removing from map.
ERROR:root:kernel b7ba744a-eec1-4c0e-8493-c4bc5b8ca945 restarted failed!
```

**Comment by blink1073** [comment]
Hi @KimStebel, that looks like a problem with the install of Jupyter itself, typically resolved by using `pip install jupyter`.

**Comment by KimStebel** [comment]
Hi @blink1073, it's not a problem with the jupyter install, as the same install works fine with other kernels.

**Comment by blink1073** [comment]
I just tried `pip install metakernel_bash` from a clean conda environment with notebook v4.0.6 and it launches properly, I'm not sure what would be different about the docker build.

**Comment by KimStebel** [comment]
As I said, the docker build is built from the current master, so not 4.0.6. If you want to reproduce the issue, you can run https://hub.docker.com/r/kimstebel/thebe-demo-notebook/

**Comment by blink1073** [comment]
I am running against the current master in my default environment, and it works fine there as well.  I don't intend to provide explicit support for docker, since I don't use it.

**Comment by dsblank** [comment]
@KimStebel If you can track down the issue, I would certainly hope that we can fix or workaround... I am hoping (and expect) that metakernel will work on docker.

**Comment by KimStebel** [comment]
@dsblank: I will try to figure out what is different about the docker build compared to your dev environment. Can you describe how you set that up in the readme?

**Comment by dsblank** [comment]
There isn't really anything special about our dev environment. You can explore the .travis.yml to see the test environment:

https://github.com/Calysto/metakernel/blob/master/.travis.yml

I see that we have IPython pegged at 3.x... we could move up to 4 to see if there are issues on Travis...

**Comment by blink1073** [comment]
@dsblank, now we're testing against both: #75.

**Comment by dsblank** [comment]
Thanks @blink1073 :cake:

**Comment by dsblank** [comment]
@KimStebel The error looks to be "Cannot load module widgets" so maybe you just need ipywidgets installed.

**Comment by blink1073** [comment]
We could make widgets optional.

**Comment by dsblank** [comment]
Yes, indeed; wonder why it isn't already... need to explore...

**Comment by dsblank** [comment]
Ah, yes: needed to handle displaying them correctly. Could be refactored. But ipywidgets is also easy to install.

**Comment by blink1073** [comment]
Yes, but hard to specify.  If you're using IPython 3 then you don't need to install it.

**Comment by KimStebel** [comment]
Thank you, installing ipywidgets fixed it. :)

**Comment by dsblank** [comment]
Closing because one can install ipywidgets, and widgets are now optional.
