### ISSUE TITLE
Write output as it is generated?

### ISSUE THREAD

**Issue by sdwfrost** [Calysto/metakernel#79]
I'm writing a kernel for [MrBayes](http://mrbayes.sourceforge.net/). My first go is [here](http://github.com/sdwfrost/mrbayes_kernel) . MrBayes produces a lot of output, and hence I get a TIMEOUT error. I tried the tips mentioned [here](http://stackoverflow.com/questions/29772158/make-ipython-notebook-print-in-real-time), but it doesn't resolve the issue.

Is there a way to write output line by line, as it is generated?

**Comment by blink1073** [comment]
Hi @sdwfrost, I think the problem is this line:

https://github.com/Calysto/metakernel/blob/master/metakernel/replwrap.py#L134

Can you try changing that to `self._expect_prompt(timeout=timeout)` on your local install of metakernel?

**Comment by dsblank** [comment]
Could be a couple of issues:

1. The output just needs to be flushed 
2. It could be that the pexpect interface needs to be written to allow output to be echoed as it comes in

Hopefully @blink1073 's fix will work and we won't have to look further.

**Comment by sdwfrost** [comment]
Dear @blink1073 nk1073 ,

I changed ```replwr ap``` as you suggested, but I still get a timeout error. The buffer gets way too big, so probably just needs to be flushed - preferably line by line.

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 213, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 362, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/dist-packages/metakernel-0.11.4-py2.7.egg/metakernel/_metakernel.py", line 337, in do_execute
    retval = self.do_execute_direct(code)
  File "/home/simon/Projects/mrbayes_kernel2/mrbayes_kernel/mrbayes_kernel.py", line 105, in do_execute_direct
    resp = super(MrBayesKernel, self).do_execute_direct(code)
  File "/usr/local/lib/python2.7/dist-packages/metakernel-0.11.4-py2.7.egg/metakernel/process_metakernel.py", line 61, in do_execute_direct
    output = self.wrapper.run_command(code.rstrip(), timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/metakernel-0.11.4-py2.7.egg/metakernel/replwrap.py", line 138, in run_command
    if self._expect_prompt(timeout=timeout) == 1:
  File "/usr/local/lib/python2.7/dist-packages/metakernel-0.11.4-py2.7.egg/metakernel/replwrap.py", line 101, in _expect_prompt
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/metakernel-0.11.4-py2.7.egg/metakernel/pexpect.py", line 1649, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/metakernel-0.11.4-py2.7.egg/metakernel/pexpect.py", line 1670, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/metakernel-0.11.4-py2.7.egg/metakernel/pexpect.py", line 232, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python2.7/dist-packages/metakernel-0.11.4-py2.7.egg/metakernel/pexpect.py", line 197, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<metakernel.pexpect.spawnu object at 0x7fdae86a81d0>
version: 3.3
command: /usr/local/bin/mb
args: ['/usr/local/bin/mb']
searcher: None
buffer (last 100 chars): u'] (-6296.922) (-6293.915) (-6302.899) * (-6302.227) (-6303.771) (-6297.283) [-6295.625] -- 0:11:18\r\n'
before (last 100 chars): u'] (-6296.922) (-6293.915) (-6302.899) * (-6302.227) (-6303.771) (-6297.283) [-6295.625] -- 0:11:18\r\n'
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 8145
child_fd: 34
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
```

**Comment by blink1073** [comment]
Hmm, you're still getting a 30sec timeout, which is what I was trying to avoid with the change.  Looking at it again, we are not handling individual lines, since we are waiting for a prompt before returning from `run_command`.  This will require a change in architecture.  I don't have any spare cycles at the moment to do so.

**Comment by sdwfrost** [comment]
Is it a matter of changing the following in ```replwrap```, to include a pexpect.TIMEOUT in the expect, followed by an event handler in run_command?

```
    def _expect_prompt(self, timeout=-1):
        if self.prompt_emit_cmd:
            self.sendline(self.prompt_emit_cmd)

        try:
            return self.child.expect([self.prompt_regex, self.continuation_prompt_regex],
                                     timeout=timeout)
        except KeyboardInterrupt:
            self.child.sendintr()
            if self.prompt_emit_cmd:
                time.sleep(1.)
            try:
                self._expect_prompt(timeout=1)
            except pexpect.TIMEOUT:
                raise KeyboardInterrupt('REPL not responding to interrupt')
            raise KeyboardInterrupt

    def run_command(self, command, timeout=-1):
        """Send a command to the REPL, wait for and return output.
        :param str command: The command to send. Trailing newlines are
        not needed.
          This should be a complete block of input that will trigger execution;
          if a continuation prompt is found after sending input,
          :exc:`ValueError` will be raised.
        :param int timeout: How long to wait for the next prompt. -1 means the
          default from the :class:`pexpect.spawn` object (default 30 seconds).
          None means to wait indefinitely.
        """
        # Split up multiline commands and feed them in bit-by-bit
        cmdlines = command.splitlines()
        # splitlines ignores trailing newlines - add it back in manually
        if command.endswith('\n'):
            cmdlines.append('')
        if not cmdlines:
            raise ValueError("No command was given")

        self.sendline(cmdlines[0])
        for line in cmdlines[1:]:
            self._expect_prompt(timeout=-1)
            self.sendline(line)

        # Command was fully submitted, now wait for the next prompt
        if self._expect_prompt(timeout=timeout) == 1:
            # We got the continuation prompt - command was incomplete
            self.child.kill(signal.SIGINT)
            self._expect_prompt(timeout=-1)
            raise ValueError("Continuation prompt found -"
                             " input was incomplete:\n" + command)
        return self.child.before
```

**Comment by blink1073** [comment]
I think there will have to be a function that returns a line, and whether the command is finished, and we keep calling it until the command is finished.  So, instead of expecting the prompt, it would expect the prompt or a new line, and if it got a new line, it would return the buffer and False.
